[package]
name = "esa-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
crossterm = "0.29.0"
md-tui = "0.9.3"
ratatui = "0.30.0"
serde = { version = "1", features = ["derive"] }
toml = "0.9.11"
toml_writer = "1.0.6"
url = "2.5.8"
